baseurl = "https://www.iletaitunefoisinternet.fr"
title = "Il Ã©tait une fois internet"
theme = ["nederburg","matomo"]
languageCode = "fr-fr"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 15 #frontpage pagination

[params.matomo]
url = "https://mtm.cyphercat.eu"
id = 2

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Tout ce que vous avez toujours voulu savoir sur Internet"
  description = "Describe your website" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Skhaen"
  authorLink = "https://www.cyphercat.eu"
  copyright = [
    "&copy; 2013 / 2019 - Creative Commons BY:SA with datalove",
    "Nederburg - Hugo Theme by [Appernetic](https://appernetic.io).",
  ]

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "FAQ"
  url = "faq/"
  weight = 2

  #[[menu.main]]
  #name = "About"
  #url = "about/"
  #weight = 2

# this will also be in author bio if there is no writer.
  [params.social]
  email         = "contact@iletaitunefoisinternet.fr"
  github        = "https://github.com/skhaen/iletaitunefoisinternet.fr"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."Skhaen"]
    link    = "https://www.cyphercat.eu"
    email   = "skhaen@cyphercat.eu"
    twitter = "https://framapiaf.org/@skhaen"
    github  = "https://github.com/skhaen/iletaitunefoisinternet.fr"

    [params.writers."ieufi"]
    link    = "https://www.iletaitunefoisinternet.fr"
    email   = "contact@iletaitunefoisinternet.fr"
    github  = "https://github.com/skhaen/iletaitunefoisinternet.fr"

